name: Daily Crawl Coupang Partners

on:
  schedule:
    # 매일 오전 3시 (KST 기준 정오)에 실행
    - cron: '0 3 * * *'
  workflow_dispatch: # 수동 실행 허용

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run crawler
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COUPANG_PARTNERS_EMAIL: ${{ secrets.COUPANG_PARTNERS_EMAIL }}
          COUPANG_PARTNERS_PASSWORD: ${{ secrets.COUPANG_PARTNERS_PASSWORD }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
        run: |
          # API 엔드포인트 호출하여 크롤링 실행
          curl -X POST http://localhost:3000/api/crawl &
          # Next.js 개발 서버 실행
          npm run build
          npm start &
          sleep 10
          curl -X POST http://localhost:3000/api/crawl || echo "Crawl completed"